# Overrides to enable python-tool-assisted generations across pipelines.

stages:
  filter_problems:
    problem_field: null
    problem_template: "{prompt} {problem}"
    num_options_field: num_options
  generate_solutions:
    prompt_config: ++prompt_config=generic/default
    predicted_answer_regex_field: answer_regex
