# Limit the pipeline to generation, filtering, and SFT preparation. Should be applied after the seed data is generated.

stages:
  filter_problems:
    enabled: False
  decontaminate:
    enabled: False
  topics_labeling:
    enabled: False
  difficulty_estimation:
    enabled: False
  generate_solutions:
    generation_kwargs:
      args:
        input_file: ${input_file}
    dependencies:
      - initial_dependency
  aggregate:
    metadata_files:
      - ${input_file}
  filter_solutions:
    input_file: ${input_file}
    only_correct_solutions: True
    is_ground_truth_answer_present: True
    metadata_values: null
